# Ref: https://developer.wordpress.org/advanced-administration/server/web-server/nginx/

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    # Ref: https://www.digitalocean.com/community/tutorials/php-fpm-nginx
    # if we don't use this container for displaying html, don't need this following line
    location / {
        root    /srv/www/wordpress;
        index   index.php index.html;
        try_files $uri $uri/ /index.php$is_args$args;

        location ~ \.php$ {
            fastcgi_pass wordpress:9000; # use service name instead of localhost cuz due to connect other containers
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    location /phpmyadmin {
        root    /var/www;
        index   index.php index.html;
        try_files $uri $uri/ /phpmyadmin/index.php$is_args$args;

        location ~ \.php$ {
            fastcgi_pass phpmyadmin:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}

server {
    # listens both on IPv4 and IPv6 on 443 and enables HTTPS and HTTP/2 support.
    # HTTP/2 is available in nginx 1.9.5 and above.
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;

    # indicate the server name
    server_name _;

    # indicate locations of SSL key files.
    ssl_certificate /etc/nginx/ssl/ssl.crt;
    ssl_certificate_key /etc/nginx/ssl/ssl.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Enable HSTS. This forces SSL on clients that respect it, most modern browsers. The includeSubDomains flag is optional.
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

    # Set caches, protocols, and accepted ciphers. This config will merit an A+ SSL Labs score as of Sept 2015.
    ssl_session_cache shared:SSL:20m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5';

    # Ref: https://www.digitalocean.com/community/tutorials/php-fpm-nginx
    # if we don't use this container for displaying html, don't need this following line
    location / {
        root    /srv/www/wordpress;
        index   index.php index.html;
        try_files $uri $uri/ /index.php$is_args$args;

        location ~ \.php$ {
            fastcgi_pass wordpress:9000; # use service name instead of localhost cuz due to connect other containers
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS on;
        }
    }

    location /phpmyadmin {
        root    /var/www;
        index   index.php index.html;
        try_files $uri $uri/ /phpmyadmin/index.php$is_args$args;

        location ~ \.php$ {
            fastcgi_pass phpmyadmin:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTPS on;
        }
    }
}
