[servers]
scw_server ansible_host=151.115.151.142 ansible_connection=ssh ansible_user=root
vagrant ansible_host=127.0.0.1 ansible_port=2222 ansible_connection=ssh ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/default/virtualbox/private_key
