[servers]
scw_server ansible_host=151.115.151.142 ansible_connection=ssh ansible_user=root
vagrant ansible_host=192.168.56.10 ansible_port=22 ansible_user=vagrant ansible_ssh_private_key_file=/home/ketzon/cloud-1/src/.vagrant/machines/fbessonS/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

