---
 - name: Play test
   hosts: servers
   vars:
     packages:
      - name: vim
        required: true
      - name: neofetch
        required: true
      - name: cowsay
        required: false
   tasks:
     - name: 'Install predefined packages on scw server'
       apt: 
            name: "{{ item.name }}"
            state: present
       when: item.required == True 
        
       loop: "{{ packages }}"

     # - name: 'test if we need reboot servor'
     #   command: needs-restarting -r
     #   register: needs_reboot
     #   changed_when: needs_reboot.rc == 1
     #   failed_when: needs_reboot.rc not in [0, 1]
     #   become: true

...



