---
- name: Play test
  hosts: servers
  become: true

  vars:
    packages:
      - name: vim
        required: true
      - name: neofetch
        required: true
      - name: cowsay
        required: false

  tasks:
    - name: Enable universe repository
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install predefined packages
      apt:
        name: "{{ item.name }}"
        state: present
      when: item.required | bool
      loop: "{{ packages }}"
