Vagrant.configure("2") do |config|

    config.vm.box = "debian/bookworm64"
    config.vm.synced_folder "./src", "/home/vagrant/src", disabled: false
    config.vm.synced_folder "./ansible", "/home/vagrant/ansible", disabled: false

    config.vm.network "private_network", ip: "192.168.56.110"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "8192"
        vb.cpus = 4
    end

    # install ansible
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "./ansible/playbook.yml"
        ansible.inventory_path = "./ansible/config/hosts.ini"
        ansible.galaxy_role_file = "./ansible/config/requirements.yml"
        ansible.version = "latest"
        ansible.limit = "all" # In order to connect all VM
    end
end
