# Ref: https://qiita.com/iineineno03k/items/6842941a18b37879e806
# Ref: https://zenn.dev/y_mrok/books/ansible-no-tsukaikata/viewer/chapter8
# ansible-playbook -i ansible/hosts.ini ansible/playbook.yml

---
- name: setup vagrant vm
  hosts: hostserver
  become: yes

  tasks:
    - name: update apt
      apt:
        update_cache: yes

    - name: install make
      apt:
        name: make
        state: present

- name: setup scaleway server
  hosts: webserver
  become: yes

  tasks:
    - name: move src to webserver
      copy:
        src: /home/vagrant/src/
        dest: /root/cloud-1/
        mode: '0755'
