name: cloud1

services:
  nginx:
    container_name: nginx
    build: ./requirement/NGINX/.
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./requirement/MariaDB/.
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
  
  phpmyadmin:
    container_name: phpmyadmin
    build: ./requirement/Phpmyadmin/.
    expose:
      - "9000"
  
  wordpress:
    container_name: wordpress
    build: ./requirement/WordPress
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/srv/www/wordpress

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_VOLUME_PATH}
      o: bind

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${WORDPRESS_VOLUME_PATH}
      o: bind
